classDiagram
    
    Construct <|-- Graph
    Construct : +generate(input)
    Construct : +loadContent(graphContent)
    Construct : +unloadContent(graphContent)
    Construct : +resize()
    Construct : +destroy()